using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Attack : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
<<<<<<< Updated upstream
        
=======
        if(Input.GetKeyDown(KeyCode.P))
        {
            PlayerAttack();
        }

        if(attacking)
        {
            timer += Time.deltaTime;
            if(timer >= timeToAttack)
            {
                timer = 0;
                attacking = false;
                attackArea.SetActive(attacking);
            }
        }
    }

    private void PlayerAttack()
    {
        attacking = true;
        attackArea.SetActive(attacking);
>>>>>>> Stashed changes
    }
}
